---
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: sharkbox
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    #volumes:
    #  - sharkbox-postgres:/var/lib/postgresql/data
