app:
  name: Sharkbox API
  version: @project.version@

spring:
    application:
        name: sharkbox-api

    datasource:
        url: jdbc:postgresql://localhost/sharkbox
        username: postgres
        password: mysecretpassword

    jpa:
        open-in-view: false
        # properties:
            # Temporary
            # jakarta.persistence.schema-generation.create-source: metadata
            # jakarta.persistence.schema-generation.scripts.action: create
            # jakarta.persistence.schema-generation.scripts.create-target: ddl.sql

springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/docs/swagger-ui
    displayRequestDuration: true
    docExpansion: list
    operationsSorter: method
    tagsSorter: alpha
    oauth:
      clientId: sharkbox-client
      realm: sharkbox
      appName: Sharkbox API
      usePkceWithAuthorizationCodeGrant: true

sharkbox:
  auth:
    stsServer: http://localhost:9080/realms/sharkbox
    clientId: sharkbox-client
    rolesLocation: realm_access.roles
