create table box (
    access smallint not null check (access between 0 and 2),
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    description varchar(255) not null,
    slug varchar(255) not null,
    name varchar(255) not null,
    owner varchar(255) not null,
    primary key (id),
    unique (slug)
);

create table thread (
    id bigint generated by default as identity,
    user_id bigint not null,
    box_id bigint,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone,
    type smallint not null check (type between 0 and 4),
    content text not null,
    mime_type varchar(255), 
    description varchar(255),
    title varchar(255) not null,
    primary key (id),
    foreign key (box_id) references box
);

create table comment (
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    parent_id bigint,
    thread_id bigint not null,
    updated_at timestamp(6) with time zone,
    user_id bigint not null,
    content varchar(255) not null,
    primary key (id),
    foreign key (thread_id) references thread
);
